![logo](images/untumbes.PNG)

<center><b>Prof. Dr. Jorge Zavaleta - zavaleta.jorge@gmail.com</b></center>

# Algoritmo Apriori

In [1]:
#librarys
import pandas as pd
import numpy as np
import random
#
import heapq
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder
#
from surprise import Dataset, Reader, KNNBasic
# ml
from surprise.model_selection import train_test_split

# graphics
import matplotlib.pylab as plt
%matplotlib inline
#
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Passo 1: Gerar um conjunto de dados aleatório
data = [['Leite', 'Cebola', 'Noz-Moscada', 'Feijão', 'Ovos', 'Iogurte'],
        ['Dill', 'Cebola', 'Noz-Moscada', 'Feijão', 'Ovos', 'Iogurte'],
        ['Leite', 'Maçã', 'Feijão', 'Ovos'],
        ['Leite', 'Milho', 'Noz-Moscada', 'Feijão', 'Iogurte'],
        ['Milho', 'Cebola', 'Cebola', 'Feijão', 'Sorvete', 'Ovos']]
data

[['Leite', 'Cebola', 'Noz-Moscada', 'Feijão', 'Ovos', 'Iogurte'],
 ['Dill', 'Cebola', 'Noz-Moscada', 'Feijão', 'Ovos', 'Iogurte'],
 ['Leite', 'Maçã', 'Feijão', 'Ovos'],
 ['Leite', 'Milho', 'Noz-Moscada', 'Feijão', 'Iogurte'],
 ['Milho', 'Cebola', 'Cebola', 'Feijão', 'Sorvete', 'Ovos']]

In [3]:
# Passo 2: Pré-processamento dos dados
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,Cebola,Dill,Feijão,Iogurte,Leite,Maçã,Milho,Noz-Moscada,Ovos,Sorvete
0,True,False,True,True,True,False,False,True,True,False
1,True,True,True,True,False,False,False,True,True,False
2,False,False,True,False,True,True,False,False,True,False
3,False,False,True,True,True,False,True,True,False,False
4,True,False,True,False,False,False,True,False,True,True

In [4]:
# Passo 3: Aplicar o algoritmo Apriori
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets

    support                                   itemsets
0       0.6                        frozenset({Cebola})
1       1.0                        frozenset({Feijão})
2       0.6                       frozenset({Iogurte})
3       0.6                         frozenset({Leite})
4       0.6                   frozenset({Noz-Moscada})
5       0.8                          frozenset({Ovos})
6       0.6                frozenset({Feijão, Cebola})
7       0.6                  frozenset({Ovos, Cebola})
8       0.6               frozenset({Iogurte, Feijão})
9       0.6                 frozenset({Feijão, Leite})
10      0.6           frozenset({Noz-Moscada, Feijão})
11      0.8                  frozenset({Feijão, Ovos})
12      0.6          frozenset({Iogurte, Noz-Moscada})
13      0.6          frozenset({Feijão, Ovos, Cebola})
14      0.6  frozenset({Iogurte, Feijão, Noz-Moscada})

In [5]:
# Collecting the inferred rules in a dataframe 
verduras_rules = association_rules(frequent_itemsets, metric ="confidence", min_threshold = 0.5) 
verduras_rules = verduras_rules.sort_values(['confidence', 'lift'], ascending =[False, False]) 
verduras_rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
12,frozenset({Iogurte}),frozenset({Noz-Moscada}),0.6,0.6,0.6,1.0,1.666667,0.24,inf,1.0
13,frozenset({Noz-Moscada}),frozenset({Iogurte}),0.6,0.6,0.6,1.0,1.666667,0.24,inf,1.0
20,"frozenset({Iogurte, Feijão})",frozenset({Noz-Moscada}),0.6,0.6,0.6,1.0,1.666667,0.24,inf,1.0
22,"frozenset({Noz-Moscada, Feijão})",frozenset({Iogurte}),0.6,0.6,0.6,1.0,1.666667,0.24,inf,1.0
23,frozenset({Iogurte}),"frozenset({Noz-Moscada, Feijão})",0.6,0.6,0.6,1.0,1.666667,0.24,inf,1.0
25,frozenset({Noz-Moscada}),"frozenset({Iogurte, Feijão})",0.6,0.6,0.6,1.0,1.666667,0.24,inf,1.0
3,frozenset({Cebola}),frozenset({Ovos}),0.6,0.8,0.6,1.0,1.250000,0.12,inf,0.5
15,"frozenset({Feijão, Cebola})",frozenset({Ovos}),0.6,0.8,0.6,1.0,1.250000,0.12,inf,0.5
19,frozenset({Cebola}),"frozenset({Feijão, Ovos})",0.6,0.8,0.6,1.0,1.250000,0.12,inf,0.5
1,frozenset({Cebola}),frozenset({Feijão}),0.6,1.0,0.6,1.0,1.000000,0.00,inf,0.0

>## Análisis?

>## Ventas online - Ejemplo 2

In [6]:
# Loading the Data 
data = pd.read_excel('data/Online_Retail.xlsx') 
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
#dimensions
data.shape

(541909, 8)

In [8]:
# Exploring the columns of the data 
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [9]:
# Exploring the different regions of transactions 
data.Country.unique()

<StringArray>
[      'United Kingdom',               'France',            'Australia',
          'Netherlands',              'Germany',               'Norway',
                 'EIRE',          'Switzerland',                'Spain',
               'Poland',             'Portugal',                'Italy',
              'Belgium',            'Lithuania',                'Japan',
              'Iceland',      'Channel Islands',              'Denmark',
               'Cyprus',               'Sweden',              'Austria',
               'Israel',              'Finland',              'Bahrain',
               'Greece',            'Hong Kong',            'Singapore',
              'Lebanon', 'United Arab Emirates',         'Saudi Arabia',
       'Czech Republic',               'Canada',          'Unspecified',
               'Brazil',                  'USA',   'European Community',
                'Malta',                  'RSA']
Length: 38, dtype: str

>### Limpieza de datos

In [10]:
# Stripping extra spaces in the description 
data['Description'] = data['Description'].str.strip() 
data.shape

(541909, 8)

In [11]:
# Dropping the rows without any invoice number 
data.dropna(axis = 0, subset =['InvoiceNo'], inplace = True) 
data['InvoiceNo'] = data['InvoiceNo'].astype('str') 
data.shape

(541909, 8)

In [12]:
# Dropping all transactions which were done on credit 
data = data[~data['InvoiceNo'].str.contains('C')] 
data.shape

(532621, 8)

>### Dividir los datos según la región de la transacción

In [13]:
# Transactions done in France 
cesta_France = (data[data['Country'] =="France"] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo')) 
cesta_France.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Transactions done in the United Kingdom 
cesta_UK = (data[data['Country'] =="United Kingdom"] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

In [15]:
# Transactions done in Portugal 
cesta_Por = (data[data['Country'] =="Portugal"] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

In [16]:
cesta_Sweden = (data[data['Country'] =="Sweden"] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

>### Codificación HOT de los datos

In [24]:
# Defining the hot encoding function to make the data suitable  
# for the concerned libraries 
def hot_encode(x):
    try:
        x = float(x)
    except:
        return x  # ignora valores não numéricos

    if x <= 0:
        return 0
    elif x >= 1:
        return 1
    else:
        return x

In [26]:
# Encoding the datasets 
cesta_encoded = cesta_France.map(hot_encode) 
cesta_France = cesta_encoded 
cesta_France.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
cesta_encoded = cesta_UK.map(hot_encode) 
cesta_UK = cesta_encoded

In [28]:
cesta_encoded = cesta_Por.map(hot_encode) 
cesta_Por = cesta_encoded

In [29]:
cesta_encoded = cesta_Sweden.map(hot_encode) 
cesta_Sweden = cesta_encoded

>### Construyendo los modelos y analizando los resultados
>#### Francia

In [30]:
# Building the model - freciencia de items
frq_items_france = apriori(cesta_France, min_support = 0.05, use_colnames = True)

In [31]:
# Collecting the inferred rules in a dataframe 
rules_france = association_rules(frq_items_france, metric ="lift", min_threshold = 1) 
rules_france = rules_france.sort_values(['confidence', 'lift'], ascending =[False, False]) 
rules_france.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
45,frozenset({JUMBO BAG WOODLAND ANIMALS}),frozenset({POSTAGE}),0.076531,0.765306,0.076531,1.000,1.306667,0.017961,inf,0.254144
258,"frozenset({PLASTERS IN TIN CIRCUS PARADE, RED ...",frozenset({POSTAGE}),0.051020,0.765306,0.051020,1.000,1.306667,0.011974,inf,0.247312
272,"frozenset({RED TOADSTOOL LED NIGHT LIGHT, PLAS...",frozenset({POSTAGE}),0.053571,0.765306,0.053571,1.000,1.306667,0.012573,inf,0.247978
300,"frozenset({SET/20 RED RETROSPOT PAPER NAPKINS,...",frozenset({SET/6 RED SPOTTY PAPER PLATES}),0.102041,0.127551,0.099490,0.975,7.644000,0.086474,34.897959,0.967949
301,"frozenset({SET/20 RED RETROSPOT PAPER NAPKINS,...",frozenset({SET/6 RED SPOTTY PAPER CUPS}),0.102041,0.137755,0.099490,0.975,7.077778,0.085433,34.489796,0.956294

>#### Reino Unido (United Kingdom)

In [34]:
## Building the model - requiere memoria
#frq_items_ru = apriori(cesta_UK, min_support = 0.01, use_colnames = True) 
# Collecting the inferred rules in a dataframe 
#rules_ru = association_rules(frq_items_ru, metric ="lift", min_threshold = 1) 
#rules_ru = rules_ru.sort_values(['confidence', 'lift'], ascending =[False, False]) 
#rules_ru.head()

>#### Portugal

In [33]:
## Building the model
frq_items_pt = apriori(cesta_Por, min_support = 0.05, use_colnames = True) 
# Collecting the inferred rules in a dataframe 
rules_pt = association_rules(frq_items_pt, metric ="lift", min_threshold = 1) 
rules_pt = rules_pt.sort_values(['confidence', 'lift'], ascending =[False, False]) 
rules_pt.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
1170,frozenset({SET 12 COLOUR PENCILS DOLLY GIRL}),frozenset({SET 12 COLOUR PENCILS SPACEBOY}),0.051724,0.051724,0.051724,1.0,19.333333,0.049049,inf,1.0
1171,frozenset({SET 12 COLOUR PENCILS SPACEBOY}),frozenset({SET 12 COLOUR PENCILS DOLLY GIRL}),0.051724,0.051724,0.051724,1.0,19.333333,0.049049,inf,1.0
1172,frozenset({SET 12 COLOUR PENCILS DOLLY GIRL}),frozenset({SET OF 4 KNICK KNACK TINS LONDON}),0.051724,0.051724,0.051724,1.0,19.333333,0.049049,inf,1.0
1173,frozenset({SET OF 4 KNICK KNACK TINS LONDON}),frozenset({SET 12 COLOUR PENCILS DOLLY GIRL}),0.051724,0.051724,0.051724,1.0,19.333333,0.049049,inf,1.0
1174,frozenset({SET 12 COLOUR PENCILS DOLLY GIRL}),frozenset({SET OF 4 KNICK KNACK TINS POPPIES}),0.051724,0.051724,0.051724,1.0,19.333333,0.049049,inf,1.0

>### Suecia

In [35]:
## Building the model
frq_items_su = apriori(cesta_Sweden, min_support = 0.05, use_colnames = True) 
# Collecting the inferred rules in a dataframe 
rules_su = association_rules(frq_items_su, metric ="lift", min_threshold = 1) 
rules_su = rules_su.sort_values(['confidence', 'lift'], ascending =[False, False]) 
rules_su.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,frozenset({12 PENCILS SMALL TUBE SKULL}),frozenset({PACK OF 72 SKULL CAKE CASES}),0.055556,0.055556,0.055556,1.0,18.0,0.052469,inf,1.0
1,frozenset({PACK OF 72 SKULL CAKE CASES}),frozenset({12 PENCILS SMALL TUBE SKULL}),0.055556,0.055556,0.055556,1.0,18.0,0.052469,inf,1.0
4,frozenset({36 DOILIES DOLLY GIRL}),frozenset({ASSORTED BOTTLE TOP MAGNETS}),0.055556,0.055556,0.055556,1.0,18.0,0.052469,inf,1.0
5,frozenset({ASSORTED BOTTLE TOP MAGNETS}),frozenset({36 DOILIES DOLLY GIRL}),0.055556,0.055556,0.055556,1.0,18.0,0.052469,inf,1.0
180,frozenset({CHILDRENS CUTLERY CIRCUS PARADE}),frozenset({CHILDRENS CUTLERY DOLLY GIRL}),0.055556,0.055556,0.055556,1.0,18.0,0.052469,inf,1.0

>## Análisis?

>## Minorista - Ejemplo 3

In [36]:
# Load and preprocess data set
mino_df = pd.read_csv('data/retail_dataset.csv', sep=',')
mino_df.head(10)

        0       1       2       3       4       5       6
0   Bread    Wine    Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese    Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil    Wine     NaN     NaN     NaN     NaN
5    Eggs   Bread    Wine  Pencil    Milk  Diaper   Bagel
6    Wine  Pencil    Eggs  Cheese     NaN     NaN     NaN
7   Bagel   Bread    Milk  Pencil  Diaper     NaN     NaN
8   Bread  Diaper  Cheese    Milk    Wine    Eggs     NaN
9   Bagel    Wine  Diaper    Meat  Pencil    Eggs  Cheese

In [37]:
# data shape
mino_df.shape

(315, 7)

>## Limpieza de datos

In [38]:
#tratando valores NaN
mino_df.replace(np.nan,0,inplace=True)
mino_df.head(10)

        0       1       2       3       4       5       6
0   Bread    Wine    Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese    Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat    Eggs    Milk    Wine       0       0
3  Cheese    Meat    Eggs    Milk    Wine       0       0
4    Meat  Pencil    Wine       0       0       0       0
5    Eggs   Bread    Wine  Pencil    Milk  Diaper   Bagel
6    Wine  Pencil    Eggs  Cheese       0       0       0
7   Bagel   Bread    Milk  Pencil  Diaper       0       0
8   Bread  Diaper  Cheese    Milk    Wine    Eggs       0
9   Bagel    Wine  Diaper    Meat  Pencil    Eggs  Cheese

In [39]:
# crear funcion lambda para mover los valosres x!=0 para uma lista
def removerTodosZerosLista(lista):
    return list(filter(lambda x: x!=0, lista))

In [40]:
#transformando en lista
lista_todas_transacciones = []
for index, row in mino_df.iterrows():
    lista_de_trans = row.values.tolist()
    lista_de_trans = removerTodosZerosLista(lista_de_trans)
    # adiciona a la lista general
    lista_todas_transacciones.append(lista_de_trans)
    
# visualiza lista
lista_todas_transacciones[0:10]

[['Bread', 'Wine', 'Eggs', 'Meat', 'Cheese', 'Pencil', 'Diaper'],
 ['Bread', 'Cheese', 'Meat', 'Diaper', 'Wine', 'Milk', 'Pencil'],
 ['Cheese', 'Meat', 'Eggs', 'Milk', 'Wine'],
 ['Cheese', 'Meat', 'Eggs', 'Milk', 'Wine'],
 ['Meat', 'Pencil', 'Wine'],
 ['Eggs', 'Bread', 'Wine', 'Pencil', 'Milk', 'Diaper', 'Bagel'],
 ['Wine', 'Pencil', 'Eggs', 'Cheese'],
 ['Bagel', 'Bread', 'Milk', 'Pencil', 'Diaper'],
 ['Bread', 'Diaper', 'Cheese', 'Milk', 'Wine', 'Eggs'],
 ['Bagel', 'Wine', 'Diaper', 'Meat', 'Pencil', 'Eggs', 'Cheese']]

>## Procesamiento de datos

En el análisis de asociación, el dataset de datos debe ser 1 y 0 o un tipo de estructura de datos booleano como Verdadero/Falso.

In [41]:
# One Hot Encoding process has been done.
temp = TransactionEncoder()
temp_df = temp.fit(lista_todas_transacciones).transform(lista_todas_transacciones)
minorista_df = pd.DataFrame(temp_df,columns=temp.columns_)
minorista_df.head()

   Bagel  Bread  Cheese  Diaper   Eggs  Meat   Milk  Pencil  Wine
0  False   True    True    True   True  True  False    True  True
1  False   True    True    True  False  True   True    True  True
2  False  False    True   False   True  True   True   False  True
3  False  False    True   False   True  True   True   False  True
4  False  False   False   False  False  True  False    True  True

>## Algoritmo apriori

El dataset de datos ahora es adecuado para el análisis de asociaciones. El siguiente paso será calcular e interpretar los valores de soporte y confianza.

In [42]:
# We set our support value as 20%
mino_items = apriori(minorista_df, min_support=0.20, use_colnames=True, verbose = 1)
mino_items.sort_values(by = "support", ascending = False)
mino_items[['itemsets','support']][0:15]

Processing 4 combinations | Sampling itemset size 4 3

                      itemsets   support
0           frozenset({Bagel})  0.425397
1           frozenset({Bread})  0.504762
2          frozenset({Cheese})  0.501587
3          frozenset({Diaper})  0.406349
4            frozenset({Eggs})  0.438095
5            frozenset({Meat})  0.476190
6            frozenset({Milk})  0.501587
7          frozenset({Pencil})  0.361905
8            frozenset({Wine})  0.438095
9    frozenset({Bagel, Bread})  0.279365
10    frozenset({Milk, Bagel})  0.225397
11  frozenset({Cheese, Bread})  0.238095
12  frozenset({Diaper, Bread})  0.231746
13    frozenset({Meat, Bread})  0.206349
14    frozenset({Milk, Bread})  0.279365

In [43]:
# Collecting the inferred rules in a dataframe 
mino_rules = association_rules(mino_items, metric ="confidence", min_threshold = 0.5) 
mino_rules = mino_rules.sort_values(['confidence', 'lift'], ascending =[False, False]) 
mino_rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
33,"frozenset({Meat, Milk})",frozenset({Cheese}),0.244444,0.501587,0.203175,0.831169,1.657077,0.080564,2.952137,0.524816
30,"frozenset({Meat, Eggs})",frozenset({Cheese}),0.266667,0.501587,0.215873,0.809524,1.613924,0.082116,2.616667,0.518717
31,"frozenset({Cheese, Eggs})",frozenset({Meat}),0.298413,0.476190,0.215873,0.723404,1.519149,0.073772,1.893773,0.487091
9,frozenset({Eggs}),frozenset({Cheese}),0.438095,0.501587,0.298413,0.681159,1.358008,0.078670,1.563203,0.469167
10,frozenset({Meat}),frozenset({Cheese}),0.476190,0.501587,0.323810,0.680000,1.355696,0.084958,1.557540,0.500891
29,"frozenset({Meat, Cheese})",frozenset({Eggs}),0.323810,0.438095,0.215873,0.666667,1.521739,0.074014,1.685714,0.507042
34,"frozenset({Cheese, Milk})",frozenset({Meat}),0.304762,0.476190,0.203175,0.666667,1.400000,0.058050,1.571429,0.410959
0,frozenset({Bagel}),frozenset({Bread}),0.425397,0.504762,0.279365,0.656716,1.301042,0.064641,1.442650,0.402687
11,frozenset({Cheese}),frozenset({Meat}),0.501587,0.476190,0.323810,0.645570,1.355696,0.084958,1.477891,0.526414
32,"frozenset({Meat, Cheese})",frozenset({Milk}),0.323810,0.501587,0.203175,0.627451,1.250931,0.040756,1.337845,0.296655

>### Análisis

> Podemos interpretar el dataset resultante de la siguiente manera:
> 
> Valor de soporte -> muestra que quien compra Leche y Carne compra Queso tiene un soporte de 0.2
> 
> Valor de Confianza -> muestra que el 83% de los clientes que compran Leche y Carne también compran Queso.
> 
> Valor de elevación -> muestra que las ventas de (Queso) aumentan en 1.65 para las compras con Leche y Carne.

---
<center><b>&copy;Jorge Zavaleta, Minería de Datos 2026</b></center>